site_name: XNET API Docs

theme:
  logo: https://www.xnet.company/favicon.ico
  favicon: https://www.xnet.company/favicon.ico
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.highlight
    - header.autohide
    - content.code.copy
    - navigation.footer
  hide:
    - toc
  icon:
    admonition:
      info: fontawesome/solid/circle-info
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

plugins:
  - search:
      lang: en

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences 

nav:
  - Howto: index.md
  - API Spec:
    - Authorization: api-spec/auth.md
    - Operator: api-spec/operator.md
    - Site: api-spec/site.md
    - XNODE: api-spec/xnode.md
    - Radio: api-spec/radio.md
  - About: about.md

extra_css:
  - stylesheets/extra.css

copyright: "Copyright © 2024 XNET Inc."
